%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:58 CEST 2022 using command 'downgrade(tff)'.
tff(semantics, logic, ($modal) == ([($constants) == ($rigid),($quantification) == ($constant),($modalities) == ($modal_system_S5)])).
tff(e_type, type, e: ($i > $o)).
tff(m_type, type, m: ($i > $o)).
tff(con, conjecture, ~ (((! [X:$i]: ((m(X) => {$box}((e(X) => m(X)))))) => (! [X:$i]: ({$box}((e(X) => m(X)))))))).
