%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:45 CEST 2022 using command 'downgrade(tff)'.
tff(semantics, logic, ($modal) == ([($constants) == ($rigid),($quantification) == ($constant),($modalities) == ($modal_system_S5)])).
tff(p_type, type, p: $o).
tff(q_type, type, q: $o).
tff(pel15, conjecture, ({$box}(({$box}(({$box}(p) => {$box}(q))) => ({$box}(~ ({$box}(p))) | {$box}(q)))) & {$box}((({$box}(~ ({$box}(p))) | {$box}(q)) => {$box}(({$box}(p) => {$box}(q))))))).
