%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:44 CEST 2022 using command 'downgrade(tff)'.
tff(semantics, logic, ($modal) == ([($constants) == ($rigid),($quantification) == ($constant),($modalities) == ($modal_system_S5)])).
tff(p_type, type, p: $o).
tff(q_type, type, q: $o).
tff(r_type, type, r: $o).
tff(pel10_1, axiom, {$box}(({$box}(q) => {$box}(r)))).
tff(pel10_2, axiom, {$box}(({$box}(r) => ({$box}(p) & {$box}(q))))).
tff(pel10_3, axiom, {$box}(({$box}(p) => ({$box}(q) | {$box}(r))))).
tff(pel10, conjecture, ({$box}(({$box}(p) => {$box}(q))) & {$box}(({$box}(q) => {$box}(p))))).
